config/routes.rb
Crowdfunder::Application.routes.draw do
  root :to => "welcome#index"

  get "/projects" => "projects#index", as: "projects"
  get "/projects/:id" => "projects#show", as: "project"

  resources :projects, only: [:index, :show] do
    resources :pledges, only: [:new, :create]
  end

  resources :users, except: :index
  resources :sessions

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  namespace :my do
    resources :projects # => My::ProjectsController
  end

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  attr_accessible :amount, :project_id, :user_id

  validates :user_id, :project_id, presence: true
  validates :amount, numericality: {greater_than: 0, only_integer: true}

  belongs_to :user
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :goal, :teaser, :title, :user_id
  belongs_to :user
  has_many :pledges

  validates :title, presence: true, length: {maximum: 100}
  validates :teaser, presence: true, length: {maximum: 255}
  validates :description, presence: true
  validates :goal, presence: true, numericality: {greater_than: 0, allow_blank: true}
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :first_name, :last_name, :email, :password
  has_many :projects
  has_many :pledges

  validates :first_name, :last_name, :password, :presence => true
  validates :email, uniqueness: {case_sensitive: false}
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :nav_state

  private

  def not_authenticated
  	redirect_to new_session_path, :alert => "Please login first"
  end

  def nav_state
  end
  
end

app/controllers/my/projects_controller.rb
class My::ProjectsController < ApplicationController
	before_filter :require_login
	before_filter :require_project, except: [:index, :new, :create]

	def index
		@projects = current_user.projects.order('projects.created_at DESC').all
	end

	def edit
	end

	def update
		if @project.update_attributes params[:project]
			 # redirect_to my_projects_path, notice: "Project updated!"
			 redirect_to [:my, :projects], notice: "Project updated!"
		else
			render :edit
		end
	end

	def new
		@project = current_user.projects.build
	end

	def create
		@project = current_user.projects.build params[:project]
		if @project.save
			redirect_to [:my, :projects], notice: "Project created!"
		else
			render :new
		end
	end

	def nav_state
		@nav = :my_projects
	end

	protected

	def require_project
		@project = current_user.projects.find(params[:id])
	end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
	before_filter :require_login
	before_filter :require_project

	def new
		@pledge = @project.pledges.build
	end

	def create
		@pledge = @project.pledges.build params[:pledge]
		@pledge.user = current_user

		if @pledge.save
			redirect_to @project, notice: "Nice! Thanks for pledging $#{@pledge.amount} for this project."
		else
			render :new
		end
	end

	protected
	def require_project
		@project = Project.find params[:project_id]
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	# before_filter :require_login, :only => :edit

	def index
		@projects = Project.all
	end

	def show
		@project = Project.find(params[:id])
	end

	def nav_state
		@nav = :projects
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		if @user = login(params[:email], params[:password])
			redirect_back_or_to(root_path, :notice => 'Login Successful')
		else
			flash.now.alert = "Invalid email or password" 
			render :new
		end
	end

	def destroy
		logout
		redirect_to root_url, :notice => "Successfully logged out!"
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])

		if @user.save
			auto_login(@user)
			redirect_to root_url, :notice => "Account created"
		else
			render :new, :alert => "Please try again"
		end

	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end

	def nav_state
		@nav = :home
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my/projects_helper.rb
module My::ProjectsHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.erb
<nav>
	<div class="navbar">
		<ul>
			<li class="active">
				<a href="#">Home</a>
			</li>
			<li class="active">
				<a href="/projects">Projects</a>
			</li>
		</ul>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/shared/nav' %>

	<div class="container container-downshift">
		<% if flash[:notice] %>
		<p><%= flash[:notice] %></p>
	<% end %>
	<% if flash[:alert] %>
		<div><%= flash[:alert] %></div>
	<% end %>
		<%#= render 'layouts/shared/flash' %>

		<%= yield %>
	</div>

</body>
</html>

app/views/layouts/shared/_flash.html.erb
<% if flash[:notice] %>
	<p><%= flash[:notice] %></p>
<% end %>

<% if flash[:alert] %>
	<p><%= flash[:alert] %></p>
<% end %>

app/views/layouts/shared/_nav.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="#">CrowdFunder</a>
			<div class="nav-collapse">
				<ul class="nav">
					<li class="<%= 'active' if @nav == :home %>">
						<%= link_to 'Home', :root %>
					</li>
					<li class="<%= 'active' if @nav == :projects %>">
						<%= link_to 'Projects', :projects %>
					</li>
					<% if logged_in? %>
						<li class="divider-vertical"></li>
							<li class="<%= 'active' if @nav == :my_projects %>">
								<%= link_to 'My Projects', [:my, :projects] %>
						</li>
					<% end %>
				</ul>
				<div class="pull-right">
					<% if current_user %>
						Logged in as <%= current_user.email %>
						<%= link_to 'Logout', logout_path, class: 'btn' %>
					<% else %>
						<%= link_to 'Sign up', new_user_path, class: 'btn btn-primary' %>
						<%= link_to 'Log in', login_path, class: 'btn' %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- <nav>
	<div class="navbar">
		<ul>
			<li class="active">
				<a href="#">Home</a>
			</li>
			<li class="active">
				<a href="/projects">Projects</a>
			</li>
		</ul>
	</div>
</nav> -->

app/views/my/projects/edit.html.erb
<h1>Edit Project</h1>

<%= form_for [:my, @project] do |f| %>
	<%= f.label :title, autofocus: true %>
	<%= f.text_field :title %>
	<br/>
	<%= f.submit "Update Project" %>
<% end %>

app/views/my/projects/index.html.erb
<h1>My Projects</h1>

<% @projects.each do |project| %>
	<div class="project">
		<%= project.title %>
	</div>
<% end %>

app/views/my/projects/new.html.erb
<h1>New Project</h1>

<%= form_for [:my, @project] do |f| %>
	
	<% unless f.object.errors.empty? %>
		<div class="alert alert-error">
			<strong>Try again after fixing the following things:</strong><br/>
			<ul>
				<% f.object.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<%= f.label :title %>
	<%= f.text_field :title, autofocus: true %>

	<%= f.label :teaser %>
	<%= f.text_field :teaser %>

	<%= f.label :description %>
	<%= f.text_area :description %>

	<%= f.label :goal %>
	<%= f.number_field :goal %>
	<br/>
	<%= f.submit "Publish Project" %>

<% end %>

app/views/pledges/new.html.erb
<h1>Pledge Support For: <%= @project.title %></h1>

<%= form_for [@project, @pledge] do |f| %>
	<%= f.label :amount %>
	<%= f.number_field :amount, autofocus: true %>
	<br/>
	<%= f.submit "Pledge Now" %>
<% end %>

app/views/projects/_projects.html.erb
<% @projects.each do |project| %>
	<h3><%= link_to project.title, project_path(project) %></h3>
<% end %>

app/views/projects/index.html.erb
<h1>Projects#Index</h1>
<h2>Listing projects</h2>

<%= render 'projects' %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<p><strong>Project User Name: </strong><%= @project.user.first_name %> <%= @project.user.last_name %></p>

<%= link_to 'Back This Project', new_project_pledge_path(@project) %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
	
	<% unless f.object.errors.empty? %>
		<div class="alert alert-error">
			<strong>Try again after fixing the following things:</strong><br/>
			<ul>
				<% f.object.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<%= f.label :first_name %>
	<%= f.text_field :first_name, autofocus: true %>

	<%= f.label :last_name %>
	<%= f.text_field :last_name %>

	<%= f.label :email %>
	<%= f.text_field :email %>

	<%= f.label :password %>
	<%= f.password_field :password %>
	<br/>
	<%= f.submit "Create Account" %>

<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to CrowdFunder</h1>